const FETCH_MOVIE_START = 'FETCH_MOVIE_START';
const FETCH_MOVIE_SUCCES = 'FETCH_MOVIE_SUCCES';
const FETCH_MOVIE_ERROR = 'FETCH_MOVIE_ERROR';

const ADD_TO_WATCHLIST = 'ADD_TO_WATCHLIST';
const REMOVE_FROM_WATCHLIST = 'REMOVE_FROM_WATCHLIST';

const ADD_TO_STORAGE = 'ADD_TO_STORAGE';

export {
  FETCH_MOVIE_START,
  FETCH_MOVIE_SUCCES,
  FETCH_MOVIE_ERROR,
  ADD_TO_WATCHLIST,
  REMOVE_FROM_WATCHLIST,
  ADD_TO_STORAGE,
};
